#include "model_data/head_0_gold.h"

#include "model_data/quant_input_activation.h"

#include "model_data/quant_k_weight_int_h0.h"
#include "model_data/quant_k_weight_int_h1.h"
#include "model_data/quant_k_weight_int_h2.h"
#include "model_data/quant_k_weight_int_h3.h"
#include "model_data/quant_k_weight_int_h4.h"
#include "model_data/quant_k_weight_int_h5.h"
#include "model_data/quant_k_weight_int_h6.h"
#include "model_data/quant_k_weight_int_h7.h"

#include "model_data/quant_q_weight_int_h0.h"
#include "model_data/quant_q_weight_int_h1.h"
#include "model_data/quant_q_weight_int_h2.h"
#include "model_data/quant_q_weight_int_h3.h"
#include "model_data/quant_q_weight_int_h4.h"
#include "model_data/quant_q_weight_int_h5.h"
#include "model_data/quant_q_weight_int_h6.h"
#include "model_data/quant_q_weight_int_h7.h"

#include "model_data/quant_v_weight_int_h0.h"
#include "model_data/quant_v_weight_int_h1.h"
#include "model_data/quant_v_weight_int_h2.h"
#include "model_data/quant_v_weight_int_h3.h"
#include "model_data/quant_v_weight_int_h4.h"
#include "model_data/quant_v_weight_int_h5.h"
#include "model_data/quant_v_weight_int_h6.h"
#include "model_data/quant_v_weight_int_h7.h"